[workspace]
resolver = "2"
members = [
    "bot",
    "bot-lib"
]

[profile.release]
debug = 0
incremental = true

[patch.crates-io]
serenity = {git = "https://github.com/serenity-rs/serenity", rev="658b6a7261fbde7cf59f84613f870ef7a48735c6" }
