[package]
name = "uofu-cs-discord-bot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
poise = "0.5.6"
tokio = { version = "1.33.0", features = ["rt", "macros", "rt-multi-thread"] }
rand = "0.8.5"
chrono = "0.4.31"
serde = "1.0.189"
toml = "0.8.2"