[package]
name = "uofu-cs-discord-bot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
poise = "0.6.1"
tokio = { version = "1.33.0", features = ["rt", "macros", "rt-multi-thread"] }
rand = "0.8.5"
chrono = "0.4.31"
serde = { version = "1.0.189", features = ["derive", "rc"] }
toml = "0.8.2"
regex = "1.10.2"
nom = "7.1.3"
emojis = "0.6.1"
notify = { version = "6.1.1", default-features = false, features = [
    "macos_kqueue",
] }
itertools = "0.11.0"
clap = { version = "4.4.7", features = ["derive"] }
dashmap = "5.5.3"
dotenvy = "0.15.7"
serde_with = { version = "3.4.0", features = ["chrono"] }
futures = "0.3.29"
tap = "1.0.1"
colored = "2.1.0"
lazy_static = "1.4.0"
color-eyre = "0.6"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter", "fmt"] }
tracing-log = "0.2.0"
parking_lot = "0.12.1"
fundu = { version = "2.0.0", features = ["chrono"] }
reqwest = { version = "0.12.3", features = ["json", "blocking"] }
serde_json = "1.0.116"
