[workspace]
resolver = "2"
members = ["bot", "bot-lib", "bot-llm"]

[profile.release]
debug = 0
incremental = true

[patch.crates-io]
serenity = { git = "https://github.com/serenity-rs/serenity", rev = "658b6a7261fbde7cf59f84613f870ef7a48735c6" }

[workspace.dependencies]
tokio = { version = "1.37.0", features = ["rt", "macros", "rt-multi-thread"] }
color-eyre = "0.6"
poise = "0.6.1"
tracing = "0.1.40"
bot-llm = { path = 'bot-llm' }
bot-lib = { path = 'bot-lib' }
rand = "0.8.5"
dashmap = { version = "5.5.3", features = ["inline"] }
