default_text_detect_cooldown = 45
bot_react_role_id = 1173465249823850496
default_hit_rate = 0.21
guild_id = 1065373537591894086
skip_hit_rate_text = "KINGFISHER PLEASE"
skip_duration_text = "HIT ME BABY ONE MORE TIME"

help_text = """
[KingFisher](<https://github.com/coravacav/uofu-cs-discord-bot>) is an opportunistic comedian (RNG) that was written in [Rust](<https://doc.rust-lang.org/book/>) (the greatest language) for this server (of nerds).
### Commands:
- `/help`: Display this help message.
- `/catalog <course_id>`: Get information about a course. Either add a prefix like MATH2240 or CS will be assumed.
- `/reactme`: Allow KingFisher automatic reactions to reply to your messages (including luck)
- `/ignoreme`: Disallow KingFisher automatic reactions to reply to your messages
- `/lynch <user>`: Lynch a user with the Bot React role. 6 yays or nays needed, yay for them, nay for you. You have 90 seconds.
- `/timeout <duration>`: Timeout yourself for a parsable duration (e.g. 1d, 1h, 1m). Discord sets a limit at 4 weeks.

KingFisher also sometimes really likes to react to messages. That's why he replies sometimes (21% rate, unless you're pinging Stefan or typing "luck").
"""

[[starboards]]
all_emotes = true
channel_id = 1171176750819053589
reaction_count = 6
ignored_channel_ids = [
    1103414812312088677,
    1187117571267371102,
    1105673759974764614,
    1105673781307002990,
    1197245734790111262,
    1137075190136836115,
    1065374254742372422,
]

[[responses]]
name = "rust"
ruleset = '''
r (?i)\brust
'''
content = [
    "RUST MENTIONED :crab: :crab: :crab:",
    "<@216767618923757568>",
    "Rust is simply the best programming language. Nothing else can compare. I am naming my kids Rust and Ferris.",
    "https://doc.rust-lang.org/book/",
]

[[responses]]
name = "physics"
ruleset = '''
r (?i)\bphysics
'''
content = [
    "<@237717840818470913>",
]

[[responses]]
name = "india"
ruleset = '''
r (?i)\bindia
'''
content = [
    "<@444895960577998860>",
]

[[responses]]
name = "tkinter"
ruleset = """
r (?i)tkinter
"""
content = "TKINTER MENTIONED"

[[responses]]
name = "revskill"
ruleset = """
r (?i)revskill
or
r (?i)intelligen(?:ce|t)
or
r (?i)high iq
or
r (?i)inspirational
"""
content = [
    """
> don't thinking in function
> thinking in program pipe together
""",
    "> i can just reading code understand how fast it is",
    """
I think Rust language should be renamed to Oxy.
because ocean is >> russian
> WHo do you want to become ? Ocean, or Russian ?
""",
    """
> What is a variable. If you can answer that quesiton, you can learn any language in 1 year.
> Unlearn everything and relearn from that question.
> It contains secrets of how programming language works.
""",
    """
> western music has some modes: Ionian, Dorian, Phrygian, Lydian, Mixolydian, Aeolian, and Locrian
> So you get logerian
> It's a hybrid between a talent programmer who lacks experience
""",
    """
> But ability to hack depends mostly on which food you eat.
""",
    "> The thin man are fear of everything, that's why he live longer than the fat man.",
    """
> You'll become a better React dev by learning ASM.
> So, you learnt the ASM, but still have no idea on how to manage React state ?
> That means you still not learnt ASM yet.
> I mean, manage state in ASM is harder than in Redux.
> So if you can do it well in ASM, so you can easily do it in React.
""",
    """
It's a quiz-type interview.
Not an IQ type.
They can't assess if you can fit the job or not based on those questions.
So in the end, what they get is monkeys.
Those who know everything but can't do anything.```js
class Human implement Learnable``` not ```js
class Human inherit Monkey```
""",
    """
> You dereference a pointer.
> No.
> You depointer a reference.
""",
]

[[responses]]
name = "lucky"
hit_rate = 0.000001
ruleset = """
r (?i)luck
"""
content = "EVERYONE NEEDS TO KNOW THAT THIS PERSON JUST FUCKING HIT A 1 in 1 million roll from saying \"lucky\""
unskippable = true

[[responses]]
name = "revskill low hit rate"
ruleset = """
r (?i)function
or
r (?i)program
"""
content = [
    """
> don't thinking in function
> thinking in program pipe together
""",
    "> i can just reading code understand how fast it is",
    """
I think Rust language should be renamed to Oxy.
because ocean is >> russian
> WHo do you want to become ? Ocean, or Russian ?
""",
    """
> What is a variable. If you can answer that quesiton, you can learn any language in 1 year.
> Unlearn everything and relearn from that question.
> It contains secrets of how programming language works.
""",
    """
> western music has some modes: Ionian, Dorian, Phrygian, Lydian, Mixolydian, Aeolian, and Locrian
> So you get logerian
> It's a hybrid between a talent programmer who lacks experience
""",
    """
> But ability to hack depends mostly on which food you eat.
""",
    "> The thin man are fear of everything, that's why he live longer than the fat man.",
    """
> You'll become a better React dev by learning ASM.
> So, you learnt the ASM, but still have no idea on how to manage React state ?
> That means you still not learnt ASM yet.
> I mean, manage state in ASM is harder than in Redux.
> So if you can do it well in ASM, so you can easily do it in React.
""",
    """
It's a quiz-type interview.
Not an IQ type.
They can't assess if you can fit the job or not based on those questions.
So in the end, what they get is monkeys.
Those who know everything but can't do anything.```js
class Human implement Learnable``` not ```js
class Human inherit Monkey```
""",
    """
> You dereference a pointer.
> No.
> You depointer a reference.
""",
]
hit_rate = 0.05

[[responses]]
name = "long ass word bro"
ruleset = """
r (?: |^)[a-zA-Z]{15,}(?: |$)
or
r (?i)i like your funny words
"""
content = "https://tenor.com/view/jfk-clone-high-i-like-your-funny-words-magic-man-jack-black-gif-18659433"

[[responses]]
name = "arch"
ruleset = """
r (?i)arch
!r (?i)monarch
"""
content = "i use arch btw."

[[responses]]
name = "goop"
ruleset = """
r (?i)goop
"""
content = [
    "https://tenor.com/view/gunge-gunged-slime-slimed-dunk-gif-21115557",
    "https://tenor.com/view/goop-goop-house-jello-gif-23114313",
]

[[responses]]
name = "matlab"
ruleset = """
r (?i)matlab
"""
content = [
    "https://tenor.com/view/goatee-disappointed-disappointment-no-nope-gif-12411002",
    "https://tenor.com/view/tim-gunn-eww-gross-yuck-meme-disgusting-sticks-tongue-out-gif-25378754",
    "https://tenor.com/view/what-could-be-worse-than-that-marie-winter-wentworth-worst-of-all-this-is-the-lowest-point-gif-23007250",
    "https://tenor.com/view/smarter-every-day-destin-matlab-plywood-gif-23620056",
]

[[responses]]
name = "1984"
ruleset = """
r (?i)1984
"""
content = "https://tenor.com/view/1984-gif-19260546"

[[responses]]
name = "cs major"
ruleset = '''
r (?i)cs\s*major
'''
content = "I don't get the way you guys think. I want MONEY. 6 figures out of college. 200k a year entry level. I'm in this for MONEY. I don't care about whether I'm \"fulfilled\" I want MONEY. Whatever gets me the most MONEY. What technology gets me PAID THE BEST. All I care about in this major is MONEY. That's why I'm in college, I don't wanna laugh and play with y'all. I don't wanna be buddy buddy with y'all. I'm here for MONEY."

[[responses]]
name = "stefan"
ruleset = """
r <@216767618923757568>
"""
content = "<@216767618923757568>"
cooldown = 5
hit_rate = 0.99

[[responses]]
name = "javascript"
ruleset = '''
r (?i)javascript
or
r (?i)\bjs\b
or
r (?i)\s===\s
or
r (?i)\s!==\s
'''
content = "https://tenor.com/view/if-you-cant-do-the-time-dont-do-crime-spongebob-police-close-door-gif-16367094"

[[responses]]
name = "league of legends"
ruleset = """
r (?i)league
"""
content = "Sorry for your loss."

[[responses]]
name = "mods"
ruleset = """
r (?i)mods
"""
content = "https://tenor.com/view/mods-crush-his-skull-low-tier-god-mods-crush-his-skull-cleaning-gif-27437796"

[[responses]]
name = "google maps"
ruleset = """
r (?i)google maps
"""
content = "Use two fingers to move the map :nerd::nerd::nerd:"

[[responses]]
name = "FOG"
ruleset = """
r (?i)fog
"""
content = "https://tenor.com/view/fog-fog-horn-spongebob-the-fog-scary-gif-25590686"

[[responses]]
name = "subway surfers"
ruleset = """
r (?i)((subway surfers)|(attention))    
or
r (?i)attention
"""
content = "https://tenor.com/view/subway-surfers-gif-9012698"

[[responses]]
name = "do you kiss boys with that mouth?"
ruleset = """
r (?i)boykisser
"""
content = "https://tenor.com/view/behind-scary-jumpscare-math-teacher-gif-25119908"

[[responses]]
name = "MY UNDERWEAR IS STAINED WITH AMONG US"
ruleset = """
r (?i)among.*us
"""
content = [
    "https://tenor.com/view/among-us-stop-posting-about-among-us-sus-amogus-sussy-gif-20696860",
    "https://tenor.com/view/kriziebizie-krizziebuoy-magmastuff-magstok-pootisman-gif-1255252459385296217",
    "https://tenor.com/view/among-us-gif-19075770",
]

[[responses]]
name = "society"
ruleset = """
r (?i)society if
"""
content = "https://tenor.com/view/society-if-gif-22696824"

[[responses]]
name = "bad bot"
ruleset = '''
r (?i)(((fuck)|(stfu)|(bad)).*bot\b)|(bot\b.*stfu)
'''
content = "Hitman dispatched. Do not slander me again."

[[responses]]
name = "works on my machine"
ruleset = """
r (?i)works on my machine
"""
content = "Oh, it works on your machine but not on my machine? Then perhaps, itdoesn't work, hmm?"

[[responses]]
name = "kopta"
ruleset = """
r (?i):.*k+o+p+t+a+.*:
!r <:kopta_1:1166893677617090642><:kopta_2:1166893728619831397><:kopta_3:1166893843283710052><:kopta_4:1166893878910124032>
"""
content = [
    "https://tenor.com/view/horse-horse-react-thanos-meme-gif-26303208",
    "https://tenor.com/view/thanos-point-face-with-monocle-this-man-react-him-gif-26503600",
    "https://tenor.com/view/this-man-above-me-part_alternation_mark-gif-26966077",
    "https://tenor.com/view/lobster-react-him-lobster-react-thanos-gif-26859688",
    "https://tenor.com/view/discord-gif-27442765",
]

[[responses]]
name = "hey chat"
cooldown = 300
ruleset = """
r (?i)chat
!r chatgpt
"""
content = "https://tenor.com/view/xqc-what-xqc-what-xqc-search-gif-25343378"

[[responses]]
name = "uh, meow?"
ruleset = '''
r (?i)\bme+o*w\b
or
r (?i)[ou]w[ou]
or
r :3
or
r 喵
or
r (?i)\bee+p.*
or
r (?i)ny+a+
or
r (?i)mrr+[pb]
or
r (?i)pu+rr+
'''
content = [
    "https://tenor.com/view/modern-family-spray-squirt-annoyed-irritated-gif-4445288",
]

[[responses]]
name = "chad"
ruleset = """
r (?i)chad
or
r (?i)grind
or
r (?i)based
"""
content = [
    "https://tenor.com/view/gentleman-giga-chad-sigma-male-gif-25702945",
    "https://tenor.com/view/mujikcboro-seriymujik-gif-24361533",
    "https://tenor.com/view/gigachad-chad-gif-20773266",
]

[[responses]]
name = "um ackshually"
ruleset = '''
r (?i)ackshually
or
r (?i)um\s+actually
'''
content = "https://tenor.com/view/nerd-nerd-glasses-uhm-aktually-glasses-gif-4161113894351475297"
