[package]
name = "bot-llm"
version = "0.1.0"
edition = "2021"

[dependencies]
color-eyre = {workspace = true}
tracing-subscriber = { version = "0.3.18", features = ["env-filter", "fmt"] }
indoc = "2.0.5"
candle-core = { git = "https://github.com/huggingface/candle.git", version = "0.6.1", features = ["cuda"] }
candle-nn = { git = "https://github.com/huggingface/candle.git", version = "0.6.1", features = ["cuda"] }
candle-transformers = { git = "https://github.com/huggingface/candle.git", version = "0.6.1", features = ["cuda"] }
candle-examples = { git = "https://github.com/huggingface/candle.git", version = "0.6.1", features = ["cuda"] }
tokenizers = "0.19.1"
rand.workspace = true
